### ISSUE TITLE
Crashes when attacking an entity.

### ISSUE THREAD

**Issue by SylveonBottle** [Revvilo/Responsive-Shields#1]
Upon hitting an entity in singleplayer, the game crashes.

https://mclo.gs/KQxmOI8

Minecraft version: 1.19.2
Forge version: 43.1.1 & 43.1.27

**Comment by Revvilo** [comment]
Please update the mod. You're running version 1.1, whereas 2.1 has had a complete rewrite which makes it significantly more compatible.
Feel free to reply if it continues to crash on 2.1, though.

**Comment by SylveonBottle** [comment]
My apologies, but Modrinth's latest version is v1.1. Could you please update it when you get the chance?
https://modrinth.com/mod/responsiveshields/versions

**Comment by Revvilo** [comment]
Haha, good lord, I have no idea how I forgot about that. Thanks for the heads up!
