### ISSUE TITLE
Can you make it work on servers

### ISSUE THREAD

**Issue by THORJUGGERNAUT** [Revvilo/Responsive-Shields#3]
Hey loved using your mod it was fantastic, but I get to play on my school servers and It would be even more fantastic if it works on servers

**Comment by Revvilo** [comment]
Are you asking that when it's installed on your game, it works on any server you join?
If that's the case then sadly that's simply not possible. Atleast if I understand the game correctly.

All of the logic for calculating this stuff, including keeping track of your health, is done on the server, and then it just tells your game whether or not you got hit, and your new health, etc.
So even if I made the client "disagree" with the server, it would just _look_ like you didn't get hit, when in fact you did, on the server. Basically resulting in desync issues.

Although that's all unfortunate in this case, the up side is that it makes cheating on public servers considerably more difficult, so results in the much less chaotic server experience we have today.

I'd encourage you to ask the server admin about installing it, as it doesn't require players to install anything. If they're already running something fabric compatible there's also the fabric alternative that I've linked on the mod page which does the same thing, also not requiring players to install anything, as far as I know.

I'm also so glad you've been enjoying the mod. Definitely something that vanilla should look into changing, huh ;)

**Comment by THORJUGGERNAUT** [comment]
Thanks a lot for responding. And I've also something else to ask about shields. There is this huge minecraft server pvplegacy which uses the new form of combat. Its has a plugin I believe which makes a sound whenever a player disables another players shield and the sound is basically a shield break sound but the catch is it can be heard on the both the players ends. So I was wondering if you can make that into a mod so that whenever I join any server I can get that sound. A lot of players have been requesting for this mod and is really useful. I can send you the plugin if u like but I do not know how to make it into a mod

**Comment by THORJUGGERNAUT** [comment]
Here's the server plugin In vanilla minecraft, when shields are disabled by a player it does not make any noise but if it is disabled by a mob it makes a shield break noise this plugin basically adds a shield breaking noise when a shield is disabled by a player like servers like pvplegacy
[Shield Sound Plugin.zip](https://github.com/Revvilo/Responsive-Shields/files/10910905/Shield.Sound.Plugin.zip)
