### ISSUE TITLE
Hey its me Again

### ISSUE THREAD

**Issue by THORJUGGERNAUT** [Revvilo/Responsive-Shields#4]
Thanks a lot for responding. And I've also something else to ask about shields. There is this huge minecraft server pvplegacy which uses the new form of combat. Its has a plugin I believe which makes a sound whenever a player disables another players shield and the sound is basically a shield break sound but the catch is it can be heard on the both the players ends. So I was wondering if you can make that into a mod so that whenever I join any server I can get that sound. A lot of players have been requesting for this mod and is really useful. I can send you the plugin if u like but I do not know how to make it into a mod

Here's the server plugin In vanilla minecraft, when shields are disabled by a player it does not make any noise but if it is disabled by a mob it makes a shield break noise this plugin basically adds a shield breaking noise when a shield is disabled by a player like servers like pvplegacy
[Shield Sound Plugin.zip](https://github.com/Revvilo/Responsive-Shields/files/10910905/Shield.Sound.Plugin.zip)

**Comment by Revvilo** [comment]
Hey again,

For that to work there needs to be some sort of notification sent to the client from the server. I've never really looked into that, but on the off chance it was added but never implemented with a sound, it could be possible.

I've got a lot of serious stuff going on irl at the moment so won't be making any mods any time soon, sorry.
