### ISSUE TITLE
Not Compatible With Shields+

### ISSUE THREAD

**Issue by SassyLoving** [Revvilo/Responsive-Shields#5]
When trying to launch the game with both responsive shields and shields+, the game just crashes with the exit code 1. I'm not sure why, and both mods work just fine by themselves.

**Comment by Revvilo** [comment]
Heya, terribly sorry for taking so long to respond.
I looked into this and Shields+ is doing basically the exact same thing as Responsive Shields.
From the Shields+ mod page under Other Features:

> Reduced shield windup: In vanilla when you start blocking with a shield, there's a 0.25 seconds window where you are still not blocking, this is lowered to 0.1 seconds

I'm unsure if Shields+ allows you to configure that change for their mod, but currently, there's no way to get both my mod and Shields+ to work simultaneously.
